### ISSUE TITLE
Consider adding Headers More module

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nginx#14]
We should consider adding the NGINX Headers More module to the buildpack. This module enables users to hide the "Server: nginx" header.

Links:
- Thread on Cloud Foundry slack about this - https://cloudfoundry.slack.com/archives/C02HWMDUQ/p1565964725052200
- NGINX docs - https://www.nginx.com/resources/wiki/modules/headers_more/

**Comment by arjun024** [comment]
@paketo-buildpacks/core-dependencies What do you think about this? Looks like currently `ngx_stream_module.so` is the only module available with the nginx distribution.

**Comment by TisVictress** [comment]
@ryanmoran Is this something we still want to implement?

**Comment by ryanmoran** [comment]
I'm not sure. @paketo-buildpacks/web-servers-maintainers what do you think?

**Comment by ForestEckhardt** [comment]
This issue is 2 years old. The thread referenced on it is 3 years old. The lost comment is nearly 6 months old and it is not from a user. I am going to close this issue and wait for this ask to be raised by another user at which time we can address it.
