### ISSUE TITLE
Allow included files to be templated

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/nginx#165]
## What happened?

* What were you attempting to do?
I was trying to include some templated values like `{{port}}` in a file that I was `include`-ing in my `nginx.conf`. When my app starts the included file has not be templated and NGINX fails to start.

* What did you expect to happen?
I expected that my templated files were generated with the dynamic values they require.

## Build Configuration

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

### `nginx.conf`
```
worker_processes 1;
include my-file.conf;
```

### `my-file.conf`
```
http {
  charset utf-8;
  log_format cloudfoundry 'NginxLog "$request" $status $body_bytes_sent';
  access_log /dev/stdout cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off; # Ensure that redirects don't include the internal container PORT - 8080

  server {
    listen {{port}};
    root public;
    index index.html index.htm Default.htm;
  }
}
```

## Checklist
* [x] I have included steps for reproduction.

**Comment by fg-j** [comment]
@ryanmoran Do you expect this to work recursively for all `include`s? For instance, if `my-file.conf` from the example above included the line
```
include my-other-file.conf;
```
and `my-other-file.conf` contained some templating, would you expect that `my-other-file.conf` would have the templated values filled in as well?

**Comment by arjun024** [comment]
@fg-j @emmjohnson I'm reopening this because I found that the `configure` binary would not exit non-zero when an include file does not exist. i.e. following test would fail if added to to [`cmd/configure/main_test.go:223`](https://github.com/paketo-buildpacks/nginx/blob/v0.1.0/cmd/configure/main_test.go#L223)

```
context.Focus("when an include file does not exist", func() {
        it.Before(func() {
                Expect(ioutil.WriteFile(filepath.Join(workingDir, "nginx.conf"), []byte("include donotexist.conf;"), 0644)).To(Succeed())
                command = exec.Command(path, filepath.Join(workingDir, "nginx.conf"), localModulePath, globalModulePath)
                buffer = bytes.NewBuffer(nil)
        })

        it("exits non-zero", func() {
                session, err := gexec.Start(command, buffer, buffer)
                Expect(err).ToNot(HaveOccurred())
                Eventually(session).Should(gexec.Exit(1), buffer.String)
        })
})
```

The only possible error case for `filepath.Glob` ([here](https://github.com/paketo-buildpacks/nginx/blob/v0.1.0/cmd/configure/main.go#L80)) is when the pattern is wrong. The binary must also make sure that the included file exists. Could you take a look?

**Comment by fg-j** [comment]
@arjun024 This is mainly so that this has similar behaviour to the v2b Cloud Foundry buildpack, right? (See https://github.com/cloudfoundry/nginx-buildpack/blob/0f586a732af93fd9082b7c8fc5598ecec676cb41/src/nginx/varify/varify_test.go#L145)
