### ISSUE TITLE
NGINX Paketo Buildpack should allow users to build static apps without providing a nginx.conf file

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/nginx#31]
Could we have some CNB equivalent of the [staticfile CF Buildpack](https://github.com/cloudfoundry/staticfile-buildpack) that allows users to build apps with static assets without providing a nginx.conf file?

**Comment by dmikusa-pivotal** [comment]
+1

My $0.02 would be that this is a separate CNB though. There's a pretty decent amount of logic in the static file buildpack, plus there's also no reason a static file CNB would need to be just Nginx. If it's a separate CNB, that's just responsible for generating the web server configuration, then you could potentially support other web servers also.

**Comment by kvedurmu** [comment]
Initial implementation of this looks great! We'll probably want a Language Family level Static File Paketo buildpack at some point, but we'll have a separate issue for that.
