### ISSUE TITLE
Support alternative files for nginx config

### ISSUE THREAD

**Issue by AidanDelaney** [paketo-buildpacks/nginx#328]
## What happened?

* What were you attempting to do?

My application has an nginx config file ``application-nginx.conf` and I don't want to rename it to `nginx.conf`.  The `application-nginx.conf` follows a company internal convention that makes it easy for us to find configuration files.

* What did you expect to happen?

I'd expect the buildpack to allow me to provide the configuration file in some manner.

* What was the actual behavior? Please provide log output, if possible.

Currently, the buildpack does not build an application with an nginx config file named something other than `nginx.conf`.

**Comment by ForestEckhardt** [comment]
@AidanDelaney I think that this PR implements this feature https://github.com/paketo-buildpacks/nginx/pull/373. Let me know if this does not fulfill your use case and we can work on getting your use case sorted out. I am going to close this issue for now but feel free to reopen for further discussion.
