### ISSUE TITLE
Allow location of nginx.conf to be configurable by environment variable

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/nginx#358]
Currently the location of `nginx.conf` is [hard-coded](https://github.com/paketo-buildpacks/nginx/blob/3ab658742d7b74b2de5ea43b82ad41df797187e5/build.go#L83). This buildpack would be more resilient and flexible if this were configurable.

There are a couple of use-cases for this:
* Upstream buildpacks (e.g. `php-nginx`) can instruct this buildpack as to where it can find the nginx config file that was created earlier in the build process
* Application developers can instruct this buildpack as to where their nginx configuration file is, if it is not in the root of their application directory.

I propose the following configuration:
* This buildpack optionally looks for the environment variable called `BP_NGINX_CONF_LOCATION`
* If the environment variable is unset, fall back to the default location of `/workspace/nginx.conf`
* If the environment variable is set to a relative filepath, assume that it is relative to `/workspace/`
* If the environment variable is set to an absolute filepath, use it as-is (i.e. relative to `/`

I am happy to move this to an RFC if that process is preferred.

**Comment by arjun024** [comment]
Proposal Sounds good to me.

* There was a related discussion about using bindings to provide nginx.conf (https://github.com/paketo-buildpacks/nginx/issues/281#issuecomment-931456280) - not sure if you have seen this or if it will provide any extra input but worth checking out if you haven't.

* Also, I have heard community interest about getting nginx buildpack to work on the tiny stack ([e.g.](https://paketobuildpacks.slack.com/archives/CUFT85E9X/p1644869643594109)). It would be nice to think if we have a desire for future tiny support whether using more environment variables would be tricky without a shell (direct process with configure binary running as exec.d). It's probably fine but worth checking out.

None of these are blockers. Just wanted to do a quick brain dump in case if it's helpful
