### ISSUE TITLE
Container fails to start with read-only file system

### ISSUE THREAD

**Issue by MischaFrank** [paketo-buildpacks/nginx#385]
## What happened?
I want to run the image in read-only mode (docker run --read-only ..) . The start fails.
It seems that 0-configure wants to replace some paths in the nginx.conf which is not possible because the file system is read only.

* What were you attempting to do?
Fulfil our security requirements and therefore run in read-only mode.
> Immutable (read-only) root filesystem should be enforced for containers

from the [Microsoft Azure defender for cloud recommendation reference](https://docs.microsoft.com/en-us/azure/defender-for-cloud/recommendations-reference#recs-container)

* What did you expect to happen?
Container is starting correctly.

* What was the actual behavior? Please provide log output, if possible.
Start fails with:
```
failed to create nginx.conf: open /workspace/nginx.conf: read-only file system
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_nginx/nginx/exec.d/0-configure': exit status 1
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack 0.26.0

* What buildpacks are you using? Please include versions.
id = "paketo-buildpacks/nginx"
version = "0.7.0"

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by ForestEckhardt** [comment]
Hmm interesting. This is happening because the exec.d process that interpolates our nginx configuration options runs and tries to write an `nginx.conf` even if there is no diff. It might make sense for us to check to see if there is a diff between the original and interpolated file and if there is none don't try to write anything.

**Comment by ryanmoran** [comment]
@MischaFrank I've submitted https://github.com/paketo-buildpacks/nginx/pull/400 in an attempt to resolve this. There are still a few issues with running NGINX on a read-only filesystem. I can't seem to figure out how to get NGINX to not buffer stuff to disk, but I can redirect those buffers to a location on disk where I can mount a tmpfs. Same thing with the pidfile. If you know the special directives I would need to set to run NGINX on a completely read-only root filesystem with no extra tmpfs mount, I would be happy to give that a try.
