### ISSUE TITLE
ERROR: validating buildpacks: buildpack paketo-buildpacks/nginx@0.15.3 does not support stack io.buildpacks.stacks.jammy.tiny

### ISSUE THREAD

**Issue by karlos84-sudo** [paketo-buildpacks/nginx#564]
I'm creating a builder image to use paketo builder tiny stack, but I have this error:
ERROR: validating buildpacks: buildpack paketo-buildpacks/nginx@0.15.3 does not support stack io.buildpacks.stacks.jammy.tiny
## Expected Behavior

It should to allow create builder image.
## Current Behavior

It is giving this error:
ERROR: validating buildpacks: buildpack paketo-buildpacks/nginx@0.15.3 does not support stack io.buildpacks.stacks.jammy.tiny
## Possible Solution

I think in the tiny jammy stack it should be added libraries or packages to support buildpack nginx@0.15.3
## Steps to Reproduce

1. Use https://github.com/paketo-buildpacks/builder-jammy-tiny/blob/main/builder.toml
2. Add into of builder.toml
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/nginx:0.15.3"
  version = "0.15.3"
An when you want to create an own builder with pack cli, it should can to create this new builder custom, with the command:
pack builder create custom_tiny_jammy --config ./builder.toml
## Motivations

I want to create an custom builder image using paketo jammy tiny stach with Nginx 0.15.3

**Comment by arjun024** [comment]
Hi @karlos84-sudo, thanks for creating the issue.

For a blocker why this buildpack can't run on the tiny stack, I can think of one example. NGINX is built with [pcre support](https://github.com/paketo-buildpacks/nginx/blob/2e31abf6fe72d482b6973c557dadedc94ac28305/dependency/actions/compile/entrypoint#L86) which is not available on tiny.

As to if libraries should be added to tiny to support nginx buildpack, I don't know if that will defeat the purpose of the tiny stack. Anyway that's a major discussion and needs broader community consensus, especially from the Stacks maintainer group. If you believe tiny stack should include the libraries, I'd advise you to figure out what libraries are missing, and then [propose an RFC](https://github.com/paketo-buildpacks/rfcs#why-rfc) for discussion.

I'm closing this issue, but feel free to re-open it for any further discussion.
